#Train settings---------------------------------------------------------------------------------------------------------------
train_data_dir: "/data/train"
model_save_dir: "/home/tristarAI/takehome_ws/trained_models"
experiment: "default_config"
train_split: 0.85
epochs: 20
warmup: 3
bs: 64
lr0: 0.01
lrf: 0.0001
update_lr_freq: 10
momentum: 0.9
weight_decay: 0.0001
augmentations: False

#Test settings----------------------------------------------------------------------------------------------------------------
test_data_dir: "/data/test"